PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^Movie/', include('apps.Movie.urls', namespace='Movie')),  # 电影模块
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/Notice/urls.py
from apps.Notice.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'Notice'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<noticeId>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<noticeId>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<noticeId>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<noticeId>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/Notice/models.py
from django.db import models
from tinymce.models import HTMLField


class Notice(models.Model):
    noticeId = models.AutoField(primary_key=True, verbose_name='公告id')
    title = models.CharField(max_length=80, default='', verbose_name='标题')
    content = HTMLField(max_length=5000, verbose_name='公告内容')
    publishDate = models.CharField(max_length=20, default='', verbose_name='发布时间')

    class Meta:
        db_table = 't_Notice'
        verbose_name = '新闻公告信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        notice = {
            'noticeId': self.noticeId,
            'title': self.title,
            'content': self.content,
            'publishDate': self.publishDate,
        }
        return notice


PythonProject/apps/Notice/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.Notice.models import Notice
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os


class FrontAddView(BaseView):  # 前台新闻公告添加
    def get(self,request):

        # 使用模板
        return render(request, 'Notice/notice_frontAdd.html')

    def post(self, request):
        notice = Notice() # 新建一个新闻公告对象然后获取参数
        notice.title = request.POST.get('notice.title')
        notice.content = request.POST.get('notice.content')
        notice.publishDate = request.POST.get('notice.publishDate')
        notice.save() # 保存新闻公告信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改新闻公告
    def get(self, request, noticeId):
        context = {'noticeId': noticeId}
        return render(request, 'Notice/notice_frontModify.html', context)


class FrontListView(BaseView):  # 前台新闻公告查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        title = self.getStrParam(request, 'title')
        publishDate = self.getStrParam(request, 'publishDate')
        # 然后条件组合查询过滤
        notices = Notice.objects.all()
        if title != '':
            notices = notices.filter(title__contains=title)
        if publishDate != '':
            notices = notices.filter(publishDate__contains=publishDate)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(notices, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        notices_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'notices_page': notices_page,
            'title': title,
            'publishDate': publishDate,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'Notice/notice_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示新闻公告详情页
    def get(self, request, noticeId):
        # 查询需要显示的新闻公告对象
        notice = Notice.objects.get(noticeId=noticeId)
        context = {
            'notice': notice
        }
        # 渲染模板显示
        return render(request, 'Notice/notice_frontshow.html', context)


class ListAllView(View): # 前台查询所有新闻公告
    def get(self,request):
        notices = Notice.objects.all()
        noticeList = []
        for notice in notices:
            noticeObj = {
                'noticeId': notice.noticeId,
                'title': notice.title,
            }
            noticeList.append(noticeObj)
        return JsonResponse(noticeList, safe=False)


class UpdateView(BaseView):  # Ajax方式新闻公告更新
    def get(self, request, noticeId):
        # GET方式请求查询新闻公告对象并返回新闻公告json格式
        notice = Notice.objects.get(noticeId=noticeId)
        return JsonResponse(notice.getJsonObj())

    def post(self, request, noticeId):
        # POST方式提交新闻公告修改信息更新到数据库
        notice = Notice.objects.get(noticeId=noticeId)
        notice.title = request.POST.get('notice.title')
        notice.content = request.POST.get('notice.content')
        notice.publishDate = request.POST.get('notice.publishDate')
        notice.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台新闻公告添加
    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'Notice/notice_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        notice = Notice() # 新建一个新闻公告对象然后获取参数
        notice.title = request.POST.get('notice.title')
        notice.content = request.POST.get('notice.content')
        notice.publishDate = request.POST.get('notice.publishDate')
        notice.save() # 保存新闻公告信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新新闻公告
    def get(self, request, noticeId):
        context = {'noticeId': noticeId}
        return render(request, 'Notice/notice_modify.html', context)


class ListView(BaseView):  # 后台新闻公告列表
    def get(self, request):
        # 使用模板
        return render(request, 'Notice/notice_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        title = self.getStrParam(request, 'title')
        publishDate = self.getStrParam(request, 'publishDate')
        # 然后条件组合查询过滤
        notices = Notice.objects.all()
        if title != '':
            notices = notices.filter(title__contains=title)
        if publishDate != '':
            notices = notices.filter(publishDate__contains=publishDate)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(notices, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        notices_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        noticeList = []
        for notice in notices_page:
            notice = notice.getJsonObj()
            noticeList.append(notice)
        # 构造模板页面需要的参数
        notice_res = {
            'rows': noticeList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(notice_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除新闻公告信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        noticeIds = self.getStrParam(request, 'noticeIds')
        noticeIds = noticeIds.split(',')
        count = 0
        try:
            for noticeId in noticeIds:
                Notice.objects.get(noticeId=noticeId).delete()
                count = count + 1
            message = '%s条记录删除成功！' % count
            success = True
        except Exception as e:
            message = '数据库外键约束删除失败！'
            success = False
        return JsonResponse({'success': success, 'message': message})


class OutToExcelView(BaseView):  # 导出新闻公告信息到excel并下载
    def get(self, request):
        # 收集查询参数
        title = self.getStrParam(request, 'title')
        publishDate = self.getStrParam(request, 'publishDate')
        # 然后条件组合查询过滤
        notices = Notice.objects.all()
        if title != '':
            notices = notices.filter(title__contains=title)
        if publishDate != '':
            notices = notices.filter(publishDate__contains=publishDate)
        #将查询结果集转换成列表
        noticeList = []
        for notice in notices:
            notice = notice.getJsonObj()
            noticeList.append(notice)
        # 利用pandas实现数据的导出功能
        pf = pd.DataFrame(noticeList)
        # 设置要导入到excel的列
        columns_map = {
            'noticeId': '公告id',
            'title': '标题',
            'publishDate': '发布时间',
        }
        pf = pf[columns_map.keys()]
        pf.rename(columns=columns_map, inplace=True)
        # 将空的单元格替换为空字符
        pf.fillna('', inplace=True)
        #设定文件名和导出路径
        filename = 'notices.xlsx'
        # 这个路径可以在settings中设置也可以直接手动输入
        root_path = settings.MEDIA_ROOT + '/output/'
        file_path = os.path.join(root_path, filename)
        pf.to_excel(file_path, encoding='utf-8', index=False)
        # 将生成的excel文件输出到网页下载
        file = open(file_path, 'rb')
        response = FileResponse(file)
        response['Content-Type'] = 'application/octet-stream'
        response['Content-Disposition'] = 'attachment;filename="notices.xlsx"'
        return response


PythonProject/templates/Notice/notice_add.html
{% include 'check_logstate.html' %}
{% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'css/notice.css' %}" />
<div id="noticeAddDiv">
    {% csrf_token %}
	<form id="noticeAddForm" enctype="multipart/form-data"  method="post">
		<div>
			<span class="label">标题:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="notice_title" name="notice.title" style="width:200px" />

			</span>

		</div>
		<div>
			<span class="label">公告内容:</span>
			<span class="inputControl">
				<textarea name="notice.content" id="notice_content" type="text/plain"   style="width:750px;height:500px;"></textarea>
			</span>

		</div>
		<div>
			<span class="label">发布时间:</span>
			<span class="inputControl">
				<input class="textbox" type="text" id="notice_publishDate" name="notice.publishDate" />

			</span>

		</div>
		<div class="operation">
			<a id="noticeAddButton" class="easyui-linkbutton">添加</a>
			<a id="noticeClearButton" class="easyui-linkbutton">重填</a>
		</div> 
	</form>
</div>
<script src="{% static 'js/Notice/notice_add.js' %}"></script>

PythonProject/templates/Notice/notice_frontquery_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>新闻公告查询</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="row"> 
	<div class="col-md-3 wow fadeInLeft">
		<div class="page-header">
    		<h1>新闻公告查询</h1>
		</div>
		<form name="noticeQueryForm" id="noticeQueryForm" action="{% url 'Notice:frontList' %}" class="mar_t15" method="post">
			 {% csrf_token %}
			<div class="form-group">
				<label for="title">标题:</label>
				<input type="text" id="title" name="title" value="{{ title }}" class="form-control" placeholder="请输入标题">
			</div>
			<div class="form-group">
				<label for="publishDate">发布时间:</label>
				<input type="text" id="publishDate" name="publishDate" class="form-control"  placeholder="请选择发布时间" value="{{ publishDate }}" onclick="SelectDate(this,'yyyy-MM-dd')" />
			</div>
            <input type=hidden name=currentPage value="{{ currentPage }}" />
            <button type="submit" class="btn btn-primary">查询</button>
        </form>
	</div>

		<div class="col-md-9 wow fadeInDown" data-wow-duration="0.5s">
			<div>
				<!-- Nav tabs -->
				<ul class="nav nav-tabs" role="tablist">
			    	<li><a href="{% url 'Index:index' %}">首页</a></li>
			    	<li role="presentation" class="active"><a href="#noticeListPanel" aria-controls="noticeListPanel" role="tab" data-toggle="tab">新闻公告列表</a></li>
			    	<li role="presentation" ><a href="{% url 'Notice:frontAdd' %}" style="display:none;">添加新闻公告</a></li>
				</ul>
			  	<!-- Tab panes -->
			  	<div class="tab-content">
				    <div role="tabpanel" class="tab-pane active" id="noticeListPanel">
				    		<div class="row">
				    			<div class="col-md-12 top5">
				    				<div class="table-responsive">
				    				<table class="table table-condensed table-hover">
				    					<tr class="success bold"><td>序号</td><td>公告id</td><td>标题</td><td>发布时间</td><td>操作</td></tr>
                                        {% for notice in notices_page %}
 										<tr>
 											<td>{{ startIndex|add:forloop.counter }}</td>
 											<td>{{ notice.noticeId }}</td>
 											<td>{{ notice.title }}</td>
 											<td>{{ notice.publishDate }}</td>
 											<td>
 												<a href="{% url 'Notice:frontShow' notice.noticeId  %}"><i class="fa fa-info"></i>&nbsp;查看</a>&nbsp;
 												<a href="#" onclick="noticeEdit('{{ notice.noticeId }}');" style="display:none;"><i class="fa fa-pencil fa-fw"></i>编辑</a>&nbsp;
 												<a href="#" onclick="noticeDelete('{{ notice.noticeId }}');" style="display:none;"><i class="fa fa-trash-o fa-fw"></i>删除</a>
 											</td> 
 										</tr>
 										{% endfor %}
				    				</table>
				    				</div>
				    			</div>
				    		</div>

				    		<div class="row">
					            <div class="col-md-12">
						            <nav class="pull-left">
						                <ul class="pagination">
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:-1 }},{{ totalPage }}>);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                                            {% for page in pageList %}
                                            {% if currentPage == page %}
						                        <li class="active"><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
						                    {% else %}
                                                <li><a href="#"  onclick="GoToPage({{ page }},{{ totalPage }});">{{ page }}</a></li>
                                            {% endif %}
                                            {% endfor %}
						                    <li><a href="#" onclick="GoToPage({{ currentPage|add:1 }},{{ totalPage }});"><span aria-hidden="true">&raquo;</span></a></li>
						                </ul>
						            </nav>
						            <div class="pull-right" style="line-height:75px;" >共有{{ recordNumber }}条记录，当前第{{ currentPage }}/{{ totalPage }} 页</div>
					            </div>
				            </div> 
				    </div>
				</div>
			</div>
		</div>
		</div>
	</div> 
<div id="noticeEditDialog" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" style="width:900px;" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><i class="fa fa-edit"></i>&nbsp;新闻公告信息编辑</h4>
      </div>
      <div class="modal-body" style="height:450px; overflow: scroll;">
      	<form class="form-horizontal" name="noticeEditForm" id="noticeEditForm" enctype="multipart/form-data" method="post"  class="mar_t15">
		    {% csrf_token %}
		  <div class="form-group">
			 <label for="notice_noticeId_edit" class="col-md-3 text-right">公告id:</label>
			 <div class="col-md-9"> 
			 	<input type="text" id="notice_noticeId_edit" name="notice.noticeId" class="form-control" placeholder="请输入公告id" readOnly>
			 </div>
		  </div> 
		  <div class="form-group">
		  	 <label for="notice_title_edit" class="col-md-3 text-right">标题:</label>
		  	 <div class="col-md-9">
			    <input type="text" id="notice_title_edit" name="notice.title" class="form-control" placeholder="请输入标题">
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="notice_content_edit" class="col-md-3 text-right">公告内容:</label>
		  	 <div class="col-md-9">
			 	<textarea name="notice.content" id="notice_content_edit" style="width:100%;height:400px;"></textarea>
			 </div>
		  </div>
		  <div class="form-group">
		  	 <label for="notice_publishDate_edit" class="col-md-3 text-right">发布时间:</label>
		  	 <div class="col-md-9">
                <div class="input-group date notice_publishDate_edit col-md-12" data-link-field="notice_publishDate_edit">
                    <input class="form-control" id="notice_publishDate_edit" name="notice.publishDate" size="16" type="text" value="" placeholder="请选择发布时间" readonly>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                </div>
		  	 </div>
		  </div>
		</form> 
	    <style>#noticeEditForm .form-group {margin-bottom:5px;}  </style>
      </div>
      <div class="modal-footer"> 
      	<button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
      	<button type="button" class="btn btn-primary" onclick="ajaxNoticeModify();">提交</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}"></script>
<script src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jsdate.js' %}"></script>
<script src="{% static 'tiny_mce/tiny_mce.js' %}"></script>
<script>
//实例化公告内容编辑器
    tinyMCE.init({
        selector: "#notice_content_edit",
        theme: 'advanced',
        language: "zh",
        strict_loading_mode: 1,
    });
/*跳转到查询结果的某页*/
function GoToPage(currentPage,totalPage) {
    if(currentPage==0) return;
    if(currentPage>totalPage) return;
    document.noticeQueryForm.currentPage.value = currentPage;
    document.noticeQueryForm.submit();
}

/*可以直接跳转到某页*/
function changepage(totalPage)
{
    var pageValue=document.noticeQueryForm.pageValue.value;
    if(pageValue>totalPage) {
        alert('你输入的页码超出了总页数!');
        return ;
    }
    document.noticeQueryForm.currentPage.value = pageValue;
    documentnoticeQueryForm.submit();
}

/*弹出修改新闻公告界面并初始化数据*/
function noticeEdit(noticeId) {
	$.ajax({
		url :  '/Notice/update/' + noticeId,
		type : "get",
		dataType: "json",
		success : function (notice, response, status) {
			if (notice) {
				$("#notice_noticeId_edit").val(notice.noticeId);
				$("#notice_title_edit").val(notice.title);
                tinyMCE.editors['notice_content_edit'].setContent(notice.content);
				$("#notice_publishDate_edit").val(notice.publishDate);
				$('#noticeEditDialog').modal('show');
			} else {
				alert("获取信息失败！");
			}
		}
	});
}

/*删除新闻公告信息*/
function noticeDelete(noticeId) {
    var csrf = $('input[name="csrfmiddlewaretoken"]').val();
	if(confirm("确认删除这个记录")) {
		$.ajax({
			type : "POST",
			url : "/Notice/deletes",
			data : {
				noticeIds : noticeId,
                "csrfmiddlewaretoken": csrf
			},
			success : function (obj) {
				if (obj.success) {
					alert("删除成功");
					$("#noticeQueryForm").submit();
					//location.href= basePath + "Notice/frontlist";
				}
				else 
					alert(obj.message);
			},
		});
	}
}

/*ajax方式提交新闻公告信息表单给服务器端修改*/
function ajaxNoticeModify() {
    $("#notice_content_edit").text(tinyMCE.editors['notice_content_edit'].getContent());
	$.ajax({
		url :   '/Notice/update/' + $("#notice_noticeId_edit").val(),
		type : "post",
		dataType: "json",
		data: new FormData($("#noticeEditForm")[0]),
		success : function (obj, response, status) {
            if(obj.success){
                alert("信息修改成功！");
                $("#noticeQueryForm").submit();
            }else{
                alert(obj.message);
            } 
		},
		processData: false,
		contentType: false,
	});
}

$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();

    /*发布时间组件*/
    $('.notice_publishDate_edit').datetimepicker({
    	language:  'zh-CN',  //语言
    	format: 'yyyy-mm-dd hh:ii:ss',
    	weekStart: 1,
    	todayBtn:  1,
    	autoclose: 1,
    	minuteStep: 1,
    	todayHighlight: 1,
    	startView: 2,
    	forceParse: 0
    });
})
</script>
</body>
</html>


PythonProject/templates/Notice/notice_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看新闻公告详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'Notice:frontList' %}">新闻公告信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">公告id:</div>
		<div class="col-md-10 col-xs-6">{{ notice.noticeId }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">标题:</div>
		<div class="col-md-10 col-xs-6">{{ notice.title }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">公告内容:</div>
		<div class="col-md-10 col-xs-6">{{ notice.content | safe  }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">发布时间:</div>
		<div class="col-md-10 col-xs-6">{{ notice.publishDate }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>
