PythonProject/PythonProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.static import serve #需要导入
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),#这部分很重要
    url(r'^Movie/', include('apps.Movie.urls', namespace='Movie')),  # 电影模块
    url(r'^UserInfo/', include('apps.UserInfo.urls', namespace='UserInfo')),  # 用户模块
    url(r'^Leaveword/', include('apps.Leaveword.urls', namespace='Leaveword')),  # 留言模块
    url(r'^Notice/', include('apps.Notice.urls', namespace='Notice')),  # 新闻公告模块

    url(r'^', include("apps.Index.urls", namespace="Index")),  # 首页模块

    url(r'^tinymce/', include('tinymce.urls')),
]

PythonProject/apps/Index/urls.py
from django.conf.urls import url
from apps.Index.views import IndexView,FrontLoginView,FrontLoginOutView,LoginView,LoginOutView,MainView,ChangePasswordView

# 正在部署的应用的名称
app_name = 'Index'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),  # 首页
    url(r'^frontLogin$', FrontLoginView.as_view(), name='frontLogin'),  # 前台登录
    url(r'^frontLoginout$', FrontLoginOutView.as_view(), name='frontLoginout'),  # 前台退出
    url(r'^login$', LoginView.as_view(), name="login"),  # 后台登录
    url(r'^loginout$', LoginOutView.as_view(), name="loginout"),  # 后台退出
    url(r'^main$', MainView.as_view(), name='main'),  # 后台主页面
    url(r'^changePassword$', ChangePasswordView.as_view(), name='changePassword')  # 管理员修改密码
]

PythonProject/apps/UserInfo/urls.py
from apps.UserInfo.views import FrontAddView, FrontListView, UpdateView, DeletesView, FrontShowView, AddView, \
    ListView, OutToExcelView, BackModifyView, FrontModifyView,FrontSelfModifyView, ListAllView
from django.conf.urls import url

# 正在部署的应用的名称
app_name = 'UserInfo'

urlpatterns = [
    url(r'^frontAdd$', FrontAddView.as_view(), name='frontAdd'),  # 前台添加
    url(r'^frontModify/(?P<user_name>.+)$', FrontModifyView.as_view(), name='frontModify'),  # 前台更新
    url(r'^frontSelfModify$', FrontSelfModifyView.as_view(), name='frontSelfModify'),  # 前台更新
    url(r'^frontList$', FrontListView.as_view(), name='frontList'),  # 前台查询列表
    url(r'^frontShow/(?P<user_name>.+)$', FrontShowView.as_view(), name='frontShow'),  # 前台显示详情页
    url(r'^listAll', ListAllView.as_view(), name='listAll'),  # 前台查询所有信息

    url(r'^update/(?P<user_name>.+)$', UpdateView.as_view(), name='update'),  # Ajax方式更新记录

    url(r'^add$', AddView.as_view(), name='add'),  # 后台添加
    url(r'^backModify/(?P<user_name>.+)$', BackModifyView.as_view(), name="backModify"),  # 后台更新
    url(r'^list$', ListView.as_view(), name='list'),  # 后台信息列表
    url(r'^deletes$', DeletesView.as_view(), name="deletes"),  # 删除记录信息
    url(r'^OutToExcel$', OutToExcelView.as_view(), name='OutToExcel')  # 导出信息到excel并下载
]

PythonProject/apps/UserInfo/models.py
from django.db import models


class UserInfo(models.Model):
    user_name = models.CharField(max_length=30, default='', primary_key=True, verbose_name='用户名')
    password = models.CharField(max_length=30, default='', verbose_name='登录密码')
    name = models.CharField(max_length=20, default='', verbose_name='姓名')
    gender = models.CharField(max_length=4, default='', verbose_name='性别')
    birthDate = models.CharField(max_length=20, default='', verbose_name='出生日期')
    userPhoto = models.ImageField(upload_to='img', max_length='100', verbose_name='用户照片')
    telephone = models.CharField(max_length=20, default='', verbose_name='联系电话')
    email = models.CharField(max_length=50, default='', verbose_name='邮箱')
    address = models.CharField(max_length=80, default='', verbose_name='家庭地址')
    regTime = models.CharField(max_length=20, default='', verbose_name='注册时间')

    class Meta:
        db_table = 't_UserInfo'
        verbose_name = '用户信息'
        verbose_name_plural = verbose_name

    def getJsonObj(self):
        userInfo = {
            'user_name': self.user_name,
            'password': self.password,
            'name': self.name,
            'gender': self.gender,
            'birthDate': self.birthDate,
            'userPhoto': self.userPhoto.url,
            'telephone': self.telephone,
            'email': self.email,
            'address': self.address,
            'regTime': self.regTime,
        }
        return userInfo


PythonProject/apps/UserInfo/views.py
from django.views.generic import View
from apps.BaseView import BaseView
from django.shortcuts import render
from django.core.paginator import Paginator
from apps.UserInfo.models import UserInfo
from django.http import JsonResponse
from django.http import FileResponse
from apps.BaseView import ImageFormatException
from django.conf import settings
import pandas as pd
import os
import datetime


class FrontAddView(BaseView):  # 前台用户添加
    def primaryKeyExist(self, user_name):  # 判断主键是否存在
        try:
            UserInfo.objects.get(user_name=user_name)
            return True
        except UserInfo.DoesNotExist:
            return False

    def get(self,request):

        # 使用模板
        return render(request, 'UserInfo/userInfo_frontAdd.html')

    def post(self, request):
        user_name = request.POST.get('userInfo.user_name') # 判断用户名是否存在
        if self.primaryKeyExist(user_name):
            return JsonResponse({'success': False, 'message': '用户名已经存在'})

        userInfo = UserInfo() # 新建一个用户对象然后获取参数
        userInfo.user_name = user_name
        userInfo.password = request.POST.get('userInfo.password')
        userInfo.name = request.POST.get('userInfo.name')
        userInfo.gender = request.POST.get('userInfo.gender')
        userInfo.birthDate = request.POST.get('userInfo.birthDate')
        try:
            userInfo.userPhoto = self.uploadImageFile(request,'userInfo.userPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        userInfo.telephone = request.POST.get('userInfo.telephone')
        userInfo.email = request.POST.get('userInfo.email')
        userInfo.address = request.POST.get('userInfo.address')
        userInfo.regTime = str(datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        userInfo.save() # 保存用户信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class FrontModifyView(BaseView):  # 前台修改用户
    def get(self, request, user_name):
        context = {'user_name': user_name}
        return render(request, 'UserInfo/userInfo_frontModify.html', context)

class FrontSelfModifyView(BaseView):  # 前台修改用户
    def get(self, request):
        context = {'user_name':  request.session.get('user_name')}
        return render(request, 'UserInfo/userInfo_frontModify.html', context)

class FrontListView(BaseView):  # 前台用户查询列表
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        self.getCurrentPage(request)  # 获取当前要显示第几页
        # 下面获取查询参数
        user_name = self.getStrParam(request, 'user_name')
        name = self.getStrParam(request, 'name')
        birthDate = self.getStrParam(request, 'birthDate')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        userInfos = UserInfo.objects.all()
        if user_name != '':
            userInfos = userInfos.filter(user_name__contains=user_name)
        if name != '':
            userInfos = userInfos.filter(name__contains=name)
        if birthDate != '':
            userInfos = userInfos.filter(birthDate__contains=birthDate)
        if telephone != '':
            userInfos = userInfos.filter(telephone__contains=telephone)
        # 对查询结果利用Paginator进行分页
        self.paginator = Paginator(userInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        userInfos_page = self.paginator.page(self.currentPage)

        # 构造模板需要的参数
        context = {
            'userInfos_page': userInfos_page,
            'user_name': user_name,
            'name': name,
            'birthDate': birthDate,
            'telephone': telephone,
            'currentPage': self.currentPage,
            'totalPage': self.totalPage,
            'recordNumber': self.recordNumber,
            'startIndex': self.startIndex,
            'pageList': self.pageList,
        }
        # 渲染模板界面
        return render(request, 'UserInfo/userInfo_frontquery_result.html', context)


class FrontShowView(View):  # 前台显示用户详情页
    def get(self, request, user_name):
        # 查询需要显示的用户对象
        userInfo = UserInfo.objects.get(user_name=user_name)
        context = {
            'userInfo': userInfo
        }
        # 渲染模板显示
        return render(request, 'UserInfo/userInfo_frontshow.html', context)


class ListAllView(View): # 前台查询所有用户
    def get(self,request):
        userInfos = UserInfo.objects.all()
        userInfoList = []
        for userInfo in userInfos:
            userInfoObj = {
                'user_name': userInfo.user_name,
                'name': userInfo.name,
            }
            userInfoList.append(userInfoObj)
        return JsonResponse(userInfoList, safe=False)


class UpdateView(BaseView):  # Ajax方式用户更新
    def get(self, request, user_name):
        # GET方式请求查询用户对象并返回用户json格式
        userInfo = UserInfo.objects.get(user_name=user_name)
        return JsonResponse(userInfo.getJsonObj())

    def post(self, request, user_name):
        # POST方式提交用户修改信息更新到数据库
        userInfo = UserInfo.objects.get(user_name=user_name)
        userInfo.password = request.POST.get('userInfo.password')
        userInfo.name = request.POST.get('userInfo.name')
        userInfo.gender = request.POST.get('userInfo.gender')
        userInfo.birthDate = request.POST.get('userInfo.birthDate')
        try:
            userPhotoName = self.uploadImageFile(request, 'userInfo.userPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        if userPhotoName != 'img/NoImage.jpg':
            userInfo.userPhoto = userPhotoName
        userInfo.telephone = request.POST.get('userInfo.telephone')
        userInfo.email = request.POST.get('userInfo.email')
        userInfo.address = request.POST.get('userInfo.address')
        userInfo.regTime = request.POST.get('userInfo.regTime')
        userInfo.save()
        return JsonResponse({'success': True, 'message': '保存成功'})

class AddView(BaseView):  # 后台用户添加
    def primaryKeyExist(self, user_name):  # 判断主键是否存在
        try:
            UserInfo.objects.get(user_name=user_name)
            return True
        except UserInfo.DoesNotExist:
            return False

    def get(self,request):

        # 渲染显示模板界面
        return render(request, 'UserInfo/userInfo_add.html')

    def post(self, request):
        # POST方式处理图书添加业务
        user_name = request.POST.get('userInfo.user_name') # 判断用户名是否存在
        if self.primaryKeyExist(user_name):
            return JsonResponse({'success': False, 'message': '用户名已经存在'})

        userInfo = UserInfo() # 新建一个用户对象然后获取参数
        userInfo.user_name = user_name
        userInfo.password = request.POST.get('userInfo.password')
        userInfo.name = request.POST.get('userInfo.name')
        userInfo.gender = request.POST.get('userInfo.gender')
        userInfo.birthDate = request.POST.get('userInfo.birthDate')
        try:
            userInfo.userPhoto = self.uploadImageFile(request,'userInfo.userPhoto')
        except ImageFormatException as ife:
            return JsonResponse({'success': False, 'message': ife.error})
        userInfo.telephone = request.POST.get('userInfo.telephone')
        userInfo.email = request.POST.get('userInfo.email')
        userInfo.address = request.POST.get('userInfo.address')
        userInfo.regTime = request.POST.get('userInfo.regTime')
        userInfo.save() # 保存用户信息到数据库
        return JsonResponse({'success': True, 'message': '保存成功'})


class BackModifyView(BaseView):  # 后台更新用户
    def get(self, request, user_name):
        context = {'user_name': user_name}
        return render(request, 'UserInfo/userInfo_modify.html', context)


class ListView(BaseView):  # 后台用户列表
    def get(self, request):
        # 使用模板
        return render(request, 'UserInfo/userInfo_query_result.html')

    def post(self, request):
        # 获取当前要显示第几页和每页几条数据
        self.getPageAndSize(request)
        # 收集查询参数
        user_name = self.getStrParam(request, 'user_name')
        name = self.getStrParam(request, 'name')
        birthDate = self.getStrParam(request, 'birthDate')
        telephone = self.getStrParam(request, 'telephone')
        # 然后条件组合查询过滤
        userInfos = UserInfo.objects.all()
        if user_name != '':
            userInfos = userInfos.filter(user_name__contains=user_name)
        if name != '':
            userInfos = userInfos.filter(name__contains=name)
        if birthDate != '':
            userInfos = userInfos.filter(birthDate__contains=birthDate)
        if telephone != '':
            userInfos = userInfos.filter(telephone__contains=telephone)
        # 利用Paginator对查询结果集分页
        self.paginator = Paginator(userInfos, self.pageSize)
        # 计算总的页码数，要显示的页码列表，总记录等
        self.calculatePages()
        # 获取第page页的Page实例对象
        userInfos_page = self.paginator.page(self.currentPage)
        # 查询的结果集转换为列表
        userInfoList = []
        for userInfo in userInfos_page:
            userInfo = userInfo.getJsonObj()
            userInfoList.append(userInfo)
        # 构造模板页面需要的参数
        userInfo_res = {
            'rows': userInfoList,
            'total': self.recordNumber,
        }
        # 渲染模板页面显示
        return JsonResponse(userInfo_res, json_dumps_params={'ensure_ascii':False})

class DeletesView(BaseView):  # 删除用户信息
    def get(self, request):
        return self.handle(request)

    def post(self, request):
        return self.handle(request)

    def handle(self, request):
        user_names = self.getStrParam(request, 'user_names')
        user_names = user_names.split(',')
        count = 0
        try:

PythonProject/templates/UserInfo/userInfo_frontAdd.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
<title>用户添加</title>
<link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
<link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
<link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
<link href="{% static 'plugins/bootstrap-datetimepicker.min.css' %}" rel="stylesheet" media="screen">
</head>
<body style="margin-top:70px;">
<div class="container">
{% include 'header.html' %}
	<div class="col-md-12 wow fadeInLeft">
		<ul class="breadcrumb">
  			<li><a href="{% url 'Index:index' %}">首页</a></li>
  			<li><a href="{% url 'UserInfo:frontList' %}">用户管理</a></li>
  			<li class="active">注册用户</li>
		</ul>
		<div class="row">
			<div class="col-md-10">
		      	<form class="form-horizontal" name="userInfoAddForm" id="userInfoAddForm" enctype="multipart/form-data" method="post"  class="mar_t15">
				    {% csrf_token %}
				  <div class="form-group">
					 <label for="userInfo_user_name" class="col-md-2 text-right">用户名:</label>
					 <div class="col-md-8"> 
					 	<input type="text" id="userInfo_user_name" name="userInfo.user_name" class="form-control" placeholder="请输入用户名">
					 </div>
				  </div> 
				  <div class="form-group">
				  	 <label for="userInfo_password" class="col-md-2 text-right">登录密码:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="userInfo_password" name="userInfo.password" class="form-control" placeholder="请输入登录密码">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="userInfo_name" class="col-md-2 text-right">姓名:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="userInfo_name" name="userInfo.name" class="form-control" placeholder="请输入姓名">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="userInfo_gender" class="col-md-2 text-right">性别:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="userInfo_gender" name="userInfo.gender" class="form-control" placeholder="请输入性别">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="userInfo_birthDateDiv" class="col-md-2 text-right">出生日期:</label>
				  	 <div class="col-md-8">
		                <div id="userInfo_birthDateDiv" class="input-group date userInfo_birthDate col-md-12" data-link-field="userInfo_birthDate" data-link-format="yyyy-mm-dd">
		                    <input class="form-control" id="userInfo_birthDate" name="userInfo.birthDate" size="16" type="text" value="" placeholder="请选择出生日期" readonly>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="userInfo_userPhoto" class="col-md-2 text-right">用户照片:</label>
				  	 <div class="col-md-8">
					    <img  class="img-responsive" id="userInfo_userPhotoImg" border="0px"/><br/>
							    <input id="userInfo_userPhoto" name="userInfo.userPhoto" type="file" size="50" />
				  	 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="userInfo_telephone" class="col-md-2 text-right">联系电话:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="userInfo_telephone" name="userInfo.telephone" class="form-control" placeholder="请输入联系电话">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="userInfo_email" class="col-md-2 text-right">邮箱:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="userInfo_email" name="userInfo.email" class="form-control" placeholder="请输入邮箱">
					 </div>
				  </div>
				  <div class="form-group">
				  	 <label for="userInfo_address" class="col-md-2 text-right">家庭地址:</label>
				  	 <div class="col-md-8">
					    <input type="text" id="userInfo_address" name="userInfo.address" class="form-control" placeholder="请输入家庭地址">
					 </div>
				  </div>
				  <div class="form-group" style="display:none;">
				  	 <label for="userInfo_regTimeDiv" class="col-md-2 text-right">注册时间:</label>
				  	 <div class="col-md-8">
		                <div id="userInfo_regTimeDiv" class="input-group date userInfo_regTime col-md-12" data-link-field="userInfo_regTime">
		                    <input class="form-control" id="userInfo_regTime" name="userInfo.regTime" size="16" type="text" value="" placeholder="请选择注册时间" readonly>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-remove"></span></span>
		                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
		                </div>
				  	 </div>
				  </div>
		          <div class="form-group">
		             <span class="col-md-2""></span>
		             <span onclick="ajaxUserInfoAdd();" class="btn btn-primary bottom5 top5">注册</span>
		          </div> 
		          <style>#userInfoAddForm .form-group {margin:5px;}  </style>  
				</form> 
			</div>
			<div class="col-md-2"></div> 
	    </div>
	</div>
</div>
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script src="{% static 'plugins/bootstrapvalidator/js/bootstrapValidator.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/bootstrap-datetimepicker.min.js' %}" charset="UTF-8"></script>
<script type="text/javascript" src="{% static 'plugins/locales/bootstrap-datetimepicker.zh-CN.js' %}" charset="UTF-8"></script>
<script>
	//提交添加用户信息
	function ajaxUserInfoAdd() { 
		//提交之前先验证表单
		$("#userInfoAddForm").data('bootstrapValidator').validate();
		if(!$("#userInfoAddForm").data('bootstrapValidator').isValid()){
			return;
		}
		jQuery.ajax({
			type : "post",
			url : "{% url 'UserInfo:frontAdd' %}",
			dataType : "json" , 
			data: new FormData($("#userInfoAddForm")[0]),
			success : function(obj) {
				if(obj.success){ 
					alert("保存成功！");
					location.reload();
				} else {
					alert(obj.message);
				}
			},
			processData: false, 
			contentType: false, 
		});
	} 
$(function(){
	/*小屏幕导航点击关闭菜单*/
    $('.navbar-collapse a').click(function(){
        $('.navbar-collapse').collapse('hide');
    });
    new WOW().init();
	//验证用户添加表单字段
	$('#userInfoAddForm').bootstrapValidator({
		feedbackIcons: {
			valid: 'glyphicon glyphicon-ok',
			invalid: 'glyphicon glyphicon-remove',
			validating: 'glyphicon glyphicon-refresh'
		},
		fields: {
			"userInfo.user_name": {
				validators: {
					notEmpty: {
						message: "用户名不能为空",
					}
				}
			},
			"userInfo.password": {
				validators: {
					notEmpty: {
						message: "登录密码不能为空",
					}
				}
			},
			"userInfo.name": {
				validators: {
					notEmpty: {
						message: "姓名不能为空",
					}
				}
			},
			"userInfo.gender": {
				validators: {
					notEmpty: {
						message: "性别不能为空",
					}
				}
			},
			"userInfo.birthDate": {
				validators: {
					notEmpty: {
						message: "出生日期不能为空",
					}
				}
			},
			"userInfo.telephone": {
				validators: {
					notEmpty: {
						message: "联系电话不能为空",
					}
				}
			},
			"userInfo.email": {
				validators: {
					notEmpty: {
						message: "邮箱不能为空",
					}
				}
			},

		}
	}); 
	//出生日期组件
	$('#userInfo_birthDateDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd',
		minView: 2,
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#userInfoAddForm').data('bootstrapValidator').updateStatus('userInfo.birthDate', 'NOT_VALIDATED',null).validateField('userInfo.birthDate');
	});
	//注册时间组件
	$('#userInfo_regTimeDiv').datetimepicker({
		language:  'zh-CN',  //显示语言
		format: 'yyyy-mm-dd hh:ii:ss',
		weekStart: 1,
		todayBtn:  1,
		autoclose: 1,
		minuteStep: 1,
		todayHighlight: 1,
		startView: 2,
		forceParse: 0
	}).on('hide',function(e) {
		//下面这行代码解决日期组件改变日期后不验证的问题
		$('#userInfoAddForm').data('bootstrapValidator').updateStatus('userInfo.regTime', 'NOT_VALIDATED',null).validateField('userInfo.regTime');
	});
})
</script>
</body>
</html>

PythonProject/templates/UserInfo/userInfo_frontshow.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
  <TITLE>查看用户详情</TITLE>
  <link href="{% static 'plugins/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/bootstrap-dashen.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/font-awesome.css' %}" rel="stylesheet">
  <link href="{% static 'plugins/animate.css' %}" rel="stylesheet">
</head>
<body style="margin-top:70px;"> 
{% include 'header.html' %}
<div class="container">
	<ul class="breadcrumb">
  		<li><a href={% url 'Index:index' %}">首页</a></li>
  		<li><a href="{% url 'UserInfo:frontList' %}">用户信息</a></li>
  		<li class="active">详情查看</li>
	</ul>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">用户名:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.user_name }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">登录密码:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.password }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">姓名:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.name }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">性别:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.gender }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">出生日期:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.birthDate }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">用户照片:</div>
		<div class="col-md-10 col-xs-6"><img class="img-responsive" src="{{ userInfo.userPhoto.url }}"  border="0px"/></div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">联系电话:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.telephone }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">邮箱:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.email }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">家庭地址:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.address }}</div>
	</div>
	<div class="row bottom15"> 
		<div class="col-md-2 col-xs-4 text-right bold">注册时间:</div>
		<div class="col-md-10 col-xs-6">{{ userInfo.regTime }}</div>
	</div>
	<div class="row bottom15">
		<div class="col-md-2 col-xs-4"></div>
		<div class="col-md-6 col-xs-6">
			<button onclick="history.back();" class="btn btn-primary">返回</button>
		</div>
	</div>
</div> 
{% include 'footer.html' %}
<script src="{% static 'plugins/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap.js' %}"></script>
<script src="{% static 'plugins/wow.min.js' %}"></script>
<script>
$(function(){
        /*小屏幕导航点击关闭菜单*/
        $('.navbar-collapse a').click(function(){
            $('.navbar-collapse').collapse('hide');
        });
        new WOW().init();
 })
 </script> 
</body>
</html>
